#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PENIN-Ω · Bridge 8/8 (CORRIGIDO)
================================
Versão corrigida usando classes unificadas.
"""

from __future__ import annotations
import asyncio
import json
import time
import logging
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

# IMPORT DAS CLASSES UNIFICADAS - CORREÇÃO CRÍTICA
from penin_omega_unified_classes import (
    Candidate, PlanOmega, UnifiedOmegaState, MutationBundle, 
    ExecutionBundle, AcquisitionReport, create_plan_omega, create_unified_state
)

# =============================================================================
# CONFIGURAÇÃO
# =============================================================================

PENIN_OMEGA_ROOT = Path("/root/.penin_omega")
LOGS_PATH = PENIN_OMEGA_ROOT / "logs"
LOGS_PATH.mkdir(parents=True, exist_ok=True)

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s][PENIN-Ω-Bridge-Fixed][%(levelname)s] %(message)s',
    handlers=[
        logging.FileHandler(LOGS_PATH / "penin_omega_bridge_fixed.log"),
        logging.StreamHandler()
    ]
)

# =============================================================================
# BRIDGE CORRIGIDO
# =============================================================================

class PeninOmegaBridgeFixed:
    """Bridge corrigido usando classes unificadas."""
    
    def __init__(self):
        self.state = create_unified_state()
        self.modules = {}
        self.logger = logging.getLogger("PeninOmegaBridge")
        
    async def execute_pipeline_fixed(self, pipeline_id: str = None) -> Dict[str, Any]:
        """
        Executa pipeline completo usando classes unificadas.
        CORREÇÃO: Usa factory functions para criar objetos com parâmetros corretos.
        """
        if pipeline_id is None:
            pipeline_id = f"pipeline_{int(time.time())}"
            
        self.logger.info(f"🚀 Iniciando pipeline corrigido {pipeline_id}")
        
        try:
            # F3: Aquisição (simulado)
            self.logger.info(f"📚 F3: Aquisição de conhecimento - {pipeline_id}")
            f3_result = {
                "knowledge_items": [],
                "quality_score": 0.0,
                "timestamp": datetime.now(timezone.utc).isoformat()
            }
            
            # F4: Mutação (simulado)
            self.logger.info(f"🧬 F4: Mutação e geração - {pipeline_id}")
            f4_candidates = []
            for i in range(3):
                # Usa factory function - CORREÇÃO CRÍTICA
                candidate = Candidate(
                    cand_id=f"cand_{pipeline_id}_{i}",
                    patches={"type": f"mutation_{i}"},
                    metadata={"source": "f4_generation"},
                    score=0.5 + (i * 0.1),
                    notes=f"Generated by F4 for {pipeline_id}"
                )
                f4_candidates.append(candidate.to_dict())
            
            f4_result = {
                "candidates": f4_candidates,
                "diversity_score": 0.7,
                "timestamp": datetime.now(timezone.utc).isoformat()
            }
            
            # F5: Crisol (usando módulo corrigido)
            self.logger.info(f"⚖️  F5: Avaliação no crisol - {pipeline_id}")
            try:
                from penin_omega_5_crucible_fixed import crucible_evaluate_and_select
                f5_result = crucible_evaluate_and_select(
                    context={"pipeline_id": pipeline_id},
                    candidates=f4_candidates,
                    goals=[{"name": "optimization", "weight": 1.0}]
                )
            except ImportError:
                # Fallback se módulo não disponível
                f5_result = {
                    "verdict": "ALLOW",
                    "selected_candidates": f4_candidates[:2],
                    "metrics": {"fallback": True}
                }
            
            # F6: Auto-rewrite (simulado)
            self.logger.info(f"🔄 F6: Auto-rewrite - {pipeline_id}")
            f6_result = {
                "verdict": "ALLOW",
                "patches_applied": len(f5_result.get("selected_candidates", [])),
                "timestamp": datetime.now(timezone.utc).isoformat()
            }
            
            # Cria estado unificado - CORREÇÃO CRÍTICA
            omega_state = create_unified_state(
                rho=0.36, 
                sr_score=0.89, 
                ece=0.002, 
                ppl_ood=94.0,
                consent=True, 
                eco_ok=True, 
                uncertainty=0.10, 
                delta_linf=0.018,
                pipeline_status="completed"
            )
            
            # Cria plano usando factory function - CORREÇÃO CRÍTICA
            plan_omega = create_plan_omega(
                plan_id=f"plan_{pipeline_id}",
                constraints={"rho_max": 0.95, "sr_tau": 0.80, "ece_max": 0.01},
                budgets={"max_cost": 2.0, "max_latency_ms": 60000},
                promotion_policy={"auto_promote": True},
                policies={"safety_first": True},  # Campo que estava causando erro
                rationale=f"Pipeline {pipeline_id} - F6: {f6_result.get('verdict', 'N/A')}"
            )
            
            # Cria bundle de execução
            execution_bundle = ExecutionBundle(
                bundle_id=f"exec_{pipeline_id}",
                artifacts=[
                    {"stage": "F3", "data": f3_result},
                    {"stage": "F4", "data": f4_result},
                    {"stage": "F5", "data": f5_result},
                    {"stage": "F6", "data": f6_result}
                ],
                metrics={
                    "total_time": time.time(),
                    "success_rate": 1.0,
                    "pipeline_id": pipeline_id
                }
            )
            
            # F8: Governança (simulado)
            self.logger.info(f"🏛️  F8: Governança - {pipeline_id}")
            f8_result = {
                "governance_verdict": "APPROVED",
                "bundle_id": execution_bundle.bundle_id,
                "state": omega_state.to_dict(),
                "plan": plan_omega.to_dict(),
                "timestamp": datetime.now(timezone.utc).isoformat()
            }
            
            # Resultado final
            pipeline_result = {
                "pipeline_id": pipeline_id,
                "status": "SUCCESS",
                "stages": {
                    "F3": f3_result,
                    "F4": f4_result, 
                    "F5": f5_result,
                    "F6": f6_result,
                    "F8": f8_result
                },
                "execution_bundle": execution_bundle.to_dict(),
                "final_state": omega_state.to_dict(),
                "timestamp": datetime.now(timezone.utc).isoformat()
            }
            
            self.logger.info(f"✅ Pipeline {pipeline_id} concluído com sucesso")
            
            # Salva resultado
            results_file = LOGS_PATH / f"pipeline_{pipeline_id}_result.json"
            with open(results_file, 'w') as f:
                json.dump(pipeline_result, f, indent=2)
            
            return pipeline_result
            
        except Exception as e:
            self.logger.error(f"❌ Pipeline {pipeline_id} falhou: {e}")
            return {
                "pipeline_id": pipeline_id,
                "status": "FAILED",
                "error": str(e),
                "timestamp": datetime.now(timezone.utc).isoformat()
            }

# =============================================================================
# FUNÇÃO DE TESTE
# =============================================================================

async def test_bridge_fixed():
    """Testa o bridge corrigido."""
    bridge = PeninOmegaBridgeFixed()
    result = await bridge.execute_pipeline_fixed("test_pipeline")
    
    print(f"✅ Teste do bridge: {result['status']}")
    if result['status'] == 'SUCCESS':
        print(f"📊 Estágios concluídos: {list(result['stages'].keys())}")
    else:
        print(f"❌ Erro: {result.get('error', 'Unknown')}")
    
    return result

if __name__ == "__main__":
    asyncio.run(test_bridge_fixed())
